# Simple TensorFlow Exercises

### Task 1a
==================================================================
<li> Create two random 0-d tensors x and y of any distribution. </li>
<li> Create a TensorFlow object that returns x + y if x > y, and x - y otherwise. </li>
<li> Hint: look up tf.cond() </li>

In [11]:
import tensorflow as tf

# [] creates a tensor of shape 0-dimension
x = tf.random_uniform([])
y = tf.random_uniform([])

# Defining the 2 different functions based on x and y value
def addition():
    return tf.add(x, y)
def subtraction():
    return tf.subtract(x, y)
# cond executes the first function if the condition is met, else second function will be executed
out = tf.cond(tf.greater(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))
final_tensor = tf.cond(tf.less(x, y), subtraction, addition)

### Task 1b
==================================================================
<li> Create two 0-d tensors x and y randomly selected from the range [-1,1). </li>
<li> Return x + y if x is less than y, x - y if x is greater than y, 0 otherwise </li>
<li> Hint: look up tf.case() </li>

In [19]:
x = tf.random_uniform([], minval=-1, maxval=1)
y = tf.random_uniform([], minval=-1, maxval=1)
r = tf.case([(tf.less(x,y), addition)], default=subtraction)
print(r)
sess = tf.InteractiveSession()
print(sess.run(r))

Tensor("case_4/If_1/Merge:0", shape=(), dtype=float32)
0.698151


### Task 1c
==================================================================
<li> Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] and y as a tensor of zeros with the same shape as x. </li>
<li> Return a boolean tensor that yields True if x equals y element-wise </li>
<li> Hint: look up tf.equal() </li>

In [22]:
x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros(tf.shape(x), dtype=tf.int32)
equal_or_not = tf.equal(x, y, name="check_equality")
print(equal_or_not)
print(sess.run(equal_or_not))

Tensor("check_equality_3:0", shape=(2, 3), dtype=bool)
[[ True False False]
 [ True False False]]


### Task 1d
==================================================================
<li> Create the tensor x of value 
[29.05088806,  27.61298943,  31.19073486,  29.35532951,
30.97266006,  26.67541885,  38.08450317,  20.74983215,
34.94445419,  34.45999146,  29.06485367,  36.01657104,
27.88236427,  20.56035233,  30.20379066,  29.51215172,
33.71149445,  28.59134293,  36.05556488,  28.66994858]. </li>
<li> Get the indices of elements in x whose values are greater than 30. </li>
Hint: Use tf.where().
<li> Then extract elements whose values are greater than 30. </li>
Hint: Use tf.gather().

In [49]:
x = tf.constant([29.05088806, 27.61298943, 31.19073486, 29.35532951, 30.97266006, 26.67541885, 38.08450317, 20.74983215, 34.94445419, 34.45999146, 29.06485367, 36.01657104, 27.88236427, 20.56035233, 30.20379066, 29.51215172, 33.71149445, 28.59134293, 36.05556488, 28.66994858])
indices = tf.where(x > 30)
print(sess.run(indices))

# x is the parameters for which we want to search for the wanted elements
# indices must be an integer tensor of any dimension, usually 0-D or 1-D
wanted_elements = tf.gather(x, indices)
print(sess.run(wanted_elements))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


### Task 1e
==================================================================
<li> Create a diagonal 2-d tensor of size 6 x 6 with the diagonal values of 1, 2, ..., 6. </li>
<li> Hint: Use tf.range() and tf.diag() </li>

In [53]:
diag_tensor = tf.diag([1,2,3,4,5,6], name="diagonal_tensor")
print(sess.run(diag_tensor))

values = tf.range(1, 7)
print(sess.run(tf.diag(values)))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


### Task 1f
==================================================================
<li> Create a random 2-d tensor of size 10 x 10 from any distribution. </li>
<li> Calculate its determinant. </li>
<li> Hint: Look at tf.matrix_determinant(). </li>

In [66]:
# Random 2-D tensor with uniform distribution
uniform_dist = tf.random_uniform([10, 10])
sess.run(tf.matrix_determinant(uniform_dist))

# Random 2-D tensor with normal distribution
normal_dist = tf.random_normal([10, 10], mean=10.0, stddev=1.0)
sess.run(tf.matrix_determinant(normal_dist))

19012.264

### Task 1g
==================================================================
<li> Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9]. </li>
<li> Return the unique elements in x </li>
<li> Hint: look up tf.unique(). Keep in mind that tf.unique() returns a tuple. </li>

In [72]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
unique_values, indices = tf.unique(x)
print(sess.run(unique_values))
print(sess.run(indices))

[ 5  2  3 10  6  4  1  0  9]
[0 1 2 0 3 4 1 2 5 1 6 6 7 8]


### Task 1h
==================================================================
<li> Create two tensors x and y of shape 300 from any normal distribution, as long as they are from the same distribution. </li>

Use tf.cond() to return:<br>
1) The mean squared error of (x - y) if the average of all elements in (x - y) is negative, or <br>
2) The sum of absolute value of all elements in the tensor (x - y) otherwise.
<li> Hint: see the Huber Loss function in the lecture slides 3 </li>

In [90]:
"""x = tf.random_normal([300])
y = tf.random_normal([300])

average = tf.reduce_mean(x - y)
print(average)

def small_res():
    return tf.reduce_mean(tf.squared_difference(x, y))
def large_res():
    return tf.reduce_sum(tf.abs(x - y))
final_output = tf.cond(average < 0, small_res, large_res)


print(sess.run(final_output))"""

x = tf.random_normal([300], mean=5, stddev=1)
y = tf.random_normal([300], mean=5, stddev=1)
average = tf.reduce_mean(x - y)
def f1(): return tf.reduce_mean(tf.square(x - y))
def f2(): return tf.reduce_sum(tf.abs(x - y))
out = tf.cond(average < 0, f1, f2)
print(sess.run(out))

ValueError: Operation 'cond_17/Merge' has been marked as not fetchable.

# THE END